# Generated by Django 3.0 on 2021-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Логин')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Почта')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('1', 'Администратор'), ('2', 'Бухгалтер'), ('3', 'Менеджер'), ('4', 'Оператор интернет'), ('5', 'Оператор ктв')], default=3, max_length=15, verbose_name='Должность')),
                ('zp', models.CharField(blank=True, max_length=100, verbose_name='Зарплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Доступ')),
                ('send_email', models.BooleanField(default=True, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Аккаунты',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('roles', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('1', 'Администратор'), ('2', 'Бухгалтер'), ('3', 'Менеджер'), ('4', 'Оператор интернет'), ('5', 'Оператор ктв')], default=3, max_length=15, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
    ]
