# Generated by Django 3.0 on 2021-07-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210612_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='NewUser', max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
