# Generated by Django 3.0 on 2021-06-06 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_myuser_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatreTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inputtitle', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('textarea', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата создания')),
                ('data_dedline', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дата work')),
                ('answear', models.TextField(blank=True, verbose_name='Комментарии')),
                ('status_task', models.CharField(choices=[('1', 'В работе'), ('2', 'Закончена'), ('3', 'Отменена'), ('4', 'Не выполнена')], default=1, max_length=15, verbose_name='Статус задачи')),
                ('answear_comment', models.TextField(blank=True, verbose_name='Ответ')),
                ('time_task', models.TimeField(blank=True, default='12:00', max_length=4, verbose_name='Время выполнения')),
                ('upload_file_name', models.CharField(blank=True, max_length=255, verbose_name='Файл')),
                ('id_users', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Roles')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
                'db_table': 'createtask',
                'ordering': ('-id',),
            },
        ),
    ]
