# Generated by Django 3.0 on 2021-06-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatretasks',
            name='answear_comment',
        ),
    ]
