# Generated by Django 3.0 on 2021-06-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_creatretasks_answear_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatretasks',
            name='answear',
        ),
    ]
