# Generated by Django 3.0 on 2021-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_creatretasks_answear'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatretasks',
            name='answear',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='creatretasks',
            name='answear_comment',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
    ]
