# Generated by Django 3.0 on 2021-06-10 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210606_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatretasks',
            name='id_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='creatretasks',
            name='inputtitle',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='creatretasks',
            name='textarea',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Текст'),
        ),
    ]
