# Generated by Django 3.0 on 2021-06-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210610_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatretasks',
            name='answear',
        ),
        migrations.RemoveField(
            model_name='creatretasks',
            name='answear_comment',
        ),
    ]
