# Generated by Django 3.0 on 2021-06-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210612_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatretasks',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
    ]
