# Generated by Django 3.0 on 2021-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_creatretasks_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatretasks',
            name='file',
            field=models.FilePathField(default='txt.txt', match='*.txt'),
        ),
    ]
